name: Build and Deploy Node.js App to Azure Web App - aiavatarte

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install Dependencies
        run: npm install

      - name: Build the Project
        run: npm run build --if-present

      - name: Upload Artifact for Deployment Job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: |
            build/  # Adjust this to your actual build output directory
            !node_modules/**  # Exclude node_modules
            !**/.git/**  # Exclude git metadata
            !**/README.md  # Exclude documentation if not needed

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download Artifact from Build Job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'aiavatarte'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_70BA48F901FD429091B7F8ED297030EC }}
